{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "pizzabox.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pizzabox.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ .Values.secretName }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy | default "Owner" }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecret.remoteKey }}
{{- end }}