apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pizzabox-secrets
  namespace: pizzabox-app-ns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: pizzabox-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pizzabox/production/api
