apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: pizzabox-project
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Pizzabox application workloads
  sourceRepos:
    - https://github.com/AyushShende25/pizza-box-infra
  destinations:
    - namespace: pizzabox-*
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: networking.k8s.io
      kind: Ingress
    - group: external-secrets.io
      kind: ExternalSecret
